image: moodlehq/moodle-workplace-plugin-ci:7.1

services:
- postgres:9.6
#- mysql:5.7.26
- name: selenium/standalone-chrome:3
  alias: selenium-standalone-chrome

variables:
  MOODLE_REPO: git@git.in.moodle.com:workplace/workplacedev.git
  MOODLE_BRANCH: master
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DB: "pgsql"
#  DB: "mysqli"

before_script:
- . prepare-workplace $cibot_sshkey
- cd $CI_PROJECT_DIR/..
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-theme_workplace.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_tenant.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_wp.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_reportbuilder.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-format_wplist.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-enrol_dynamicrule.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_dynamicrule.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_organisation.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-enrol_program.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_program.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_certification.git --branch WP-1376
- moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
- cd moodle

codecheck:
  script:
  - php admin/tool/phpunit/cli/init.php
  - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
  - . check-start
  - . check version_number
  - . check language_file_sorting
  - . check moodle-plugin-ci phplint
  #- . check moodle-plugin-ci phpcpd
  #- . check moodle-plugin-ci phpmd
  - . check moodle-plugin-ci codechecker --files all --max-warnings 1 # Behat steps definitions have long lines
  - . check moodle-plugin-ci phpdoc
  - . check moodle-plugin-ci validate
  - . check moodle-plugin-ci savepoints
  - . check moodle-plugin-ci mustache
  - . check moodle-plugin-ci eslint --max-warnings 0
  - . check moodle-plugin-ci grunt
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output -v admin/tool/dataprivacy/tests/metadata_registry_test.php
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output -v lib/tests/externallib_test.php
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output -v privacy/tests/provider_test.php
  - . check moodle-plugin-ci phpunit --coverage-text
  - . check-finish

behat:
  script:
  - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
  - php admin/tool/behat/cli/init.php --add-core-features-to-theme --parallel=3 --optimize-runs=@tool_certificate
  - . check-start
  - . check moodle-plugin-ci behat --suite workplace --profile chrome
  - . check-finish
  except:
  - master
