language: php

# For javascript behat tests we need sudo
sudo: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1

addons:
 postgresql: 9.4
 firefox: "47.0.1"
 apt:
   packages:
   - openjdk-8-jre-headless

env:
 global:
  - MOODLE_REPO=git://github.com/moodlesp/moodle.git
  - MOODLE_BRANCH=MDL-57898-master
 matrix:
  - DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../../..
  - composer create-project -n --no-dev --prefer-dist --repository='{"type":"git","url":"https://github.com/moodlesp/moodle-plugin-ci","reference":"master"}' blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin moodlesp/moodle-theme_workplace
  - moodle-plugin-ci add-plugin moodlesp/moodle-tool_tenant
  - moodle-plugin-ci add-plugin moodlesp/moodle-tool_wp
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->theme = "workplace";'

script:
  - moodle-plugin-ci phplint
  # - moodle-plugin-ci phpcpd
  # - moodle-plugin-ci phpmd # too much noise from this check, maybe, some day...
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_bgimage
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_border
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_code
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_date
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_digitalsignature
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_image
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_program
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_studentname
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_text
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_userfield
  - cd moodle; vendor/bin/phpunit --testsuite certificateelement_userpicture
  - cd moodle; vendor/bin/phpunit --fail-on-risky --disallow-test-output -v admin/tool/dataprivacy/tests/metadata_registry_test.php
  - cd moodle; vendor/bin/phpunit --fail-on-risky --disallow-test-output -v lib/tests/externallib_test.php
  - cd moodle; vendor/bin/phpunit --fail-on-risky --disallow-test-output -v privacy/tests/provider_test.php
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat
